In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
root_path='/content/gdrive/MyDrive/Datasets/insulator_data/Defective_Insulators/images/'

In [ ]:
import pandas as pd
import numpy as np
import cv2
import os
from pathlib import Path
import glob
import os
import cv2
import matplotlib.pyplot as plt
from PIL import Image
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
import tensorflow_hub as hub

In [ ]:
img = cv2.imread('/content/gdrive/MyDrive/Datasets/insulator_data/Defective_Insulators/images/000.jpg', cv2.IMREAD_COLOR)
img

array([[[217, 204, 206],
        [217, 204, 206],
        [217, 204, 206],
        ...,
        [127, 126, 135],
        [127, 127, 133],
        [129, 129, 135]],

       [[217, 204, 206],
        [217, 204, 206],
        [217, 204, 206],
        ...,
        [126, 125, 134],
        [126, 126, 132],
        [127, 127, 133]],

       [[217, 204, 206],
        [217, 204, 206],
        [217, 204, 206],
        ...,
        [126, 125, 134],
        [125, 125, 131],
        [126, 126, 132]],

       ...,

       [[107, 118,  98],
        [112, 123, 103],
        [115, 126, 106],
        ...,
        [145, 146, 130],
        [138, 141, 126],
        [136, 139, 124]],

       [[111, 122, 102],
        [113, 124, 104],
        [111, 122, 102],
        ...,
        [138, 139, 123],
        [135, 138, 123],
        [131, 134, 119]],

       [[113, 124, 104],
        [113, 124, 104],
        [111, 122, 102],
        ...,
        [131, 132, 116],
        [135, 138, 123],
        [135, 138, 123]]

In [ ]:
image = []                  # used to store image data
img_label = []              # used to store image label
img_indexes = []            # used to store image name
for i in range(248):
  img = cv2.imread('/content/gdrive/MyDrive/Datasets/insulator_data/Defective_Insulators/images/'+str(f'{i:03}')+'.jpg', cv2.IMREAD_COLOR)  
    # read image using opencv 
  img = cv2.resize(img, (224,224))                                                                   #resize image 
  img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
  image.append(img)
  img_label.append(0)                             #store label of each image in img_label
  img_indexes.append(f'{i:03}')

In [ ]:
print(len(image))

248


In [ ]:
print(img_indexes[-1])

247


In [ ]:
image1 = []                  # used to store image data
img_label1 = []              # used to store image label
img_indexes1 = []            # used to store image name
for i in range(3617):
    if (os.path.exists("/content/gdrive/MyDrive/Datasets/insulator_data/Normal_Insulators/images/"+str(f'{i:04}')+'.jpg') == True):         # check if image exists or not
        img = cv2.imread('/content/gdrive/MyDrive/Datasets/insulator_data/Normal_Insulators/images/'+str(f'{i:04}')+'.jpg', cv2.IMREAD_COLOR)       # read image using opencv 
        img = cv2.resize(img, (224,224))                                                                   #resize image 
        img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
        image1.append(img)
        img_label1.append(1)                             #store label of each image in img_label
        img_indexes1.append(f'{i:03}')
    else:
        pass

In [ ]:
print(len(image1))

600


In [ ]:
final_img=np.array(image+image1)
final_label=np.array(img_label+img_label1)

In [ ]:
final_img

array([[[[206, 204, 217],
         [206, 204, 217],
         [206, 204, 217],
         ...,
         [ 53,  47,  51],
         [132, 123, 123],
         [134, 125, 126]],

        [[206, 204, 216],
         [206, 204, 216],
         [206, 204, 216],
         ...,
         [ 57,  51,  53],
         [132, 124, 123],
         [136, 127, 128]],

        [[206, 204, 215],
         [206, 204, 215],
         [206, 204, 215],
         ...,
         [ 59,  53,  53],
         [136, 128, 126],
         [139, 130, 131]],

        ...,

        [[ 88, 109, 100],
         [ 93, 114, 109],
         [ 97, 120, 112],
         ...,
         [113, 134, 133],
         [111, 132, 135],
         [108, 132, 132]],

        [[ 98, 118, 109],
         [ 99, 119, 111],
         [ 97, 117, 111],
         ...,
         [111, 129, 129],
         [114, 132, 133],
         [115, 134, 132]],

        [[104, 124, 113],
         [104, 121, 111],
         [107, 121, 114],
         ...,
         [115, 135, 134],
        

In [ ]:
print(final_label[48])

0


In [ ]:
print(final_img.shape)
print(final_img.shape[1])
print(final_img.shape[2])
f = (final_img.shape[0], final_img.shape[2])
print(f)

(848, 224, 224, 3)
224
224
(848, 224)


In [ ]:
df = pd.DataFrame(list(zip(final_img, final_label)),columns =['Image','label'])
df.head()

Image  label
0  [[[206, 204, 217], [206, 204, 217], [206, 204,...      0
1  [[[175, 184, 193], [176, 183, 193], [178, 185,...      0
2  [[[102, 109, 107], [104, 108, 111], [108, 110,...      0
3  [[[203, 207, 216], [203, 207, 216], [204, 208,...      0
4  [[[157, 183, 154], [156, 183, 152], [159, 186,...      0

In [ ]:
df = df.sample(frac = 1)

In [ ]:
df.head()

Image  label
79   [[[140, 172, 122], [140, 172, 123], [133, 166,...      0
725  [[[182, 187, 191], [181, 186, 190], [182, 186,...      1
120  [[[143, 147, 150], [148, 153, 155], [144, 153,...      0
457  [[[209, 195, 186], [207, 193, 183], [208, 194,...      1
662  [[[61, 65, 58], [58, 50, 52], [75, 63, 65], [8...      1

In [ ]:
df['Image'].shape

(848,)

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df['Image'], df.label, test_size = 0.2, random_state = 100)

In [ ]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((678,), (170,), (678,), (170,))

In [ ]:
np.array(x_train[840])/255

array([[[0.79215686, 0.81960784, 0.84705882],
        [0.76470588, 0.75294118, 0.78823529],
        [0.63921569, 0.63137255, 0.67058824],
        ...,
        [0.58823529, 0.56862745, 0.51372549],
        [0.59607843, 0.58431373, 0.5254902 ],
        [0.62352941, 0.60392157, 0.54901961]],

       [[0.55294118, 0.58823529, 0.65490196],
        [0.54509804, 0.58039216, 0.64705882],
        [0.54117647, 0.59215686, 0.63921569],
        ...,
        [0.5254902 , 0.54901961, 0.45882353],
        [0.58431373, 0.57647059, 0.52156863],
        [0.6       , 0.59607843, 0.52941176]],

       [[0.55294118, 0.58431373, 0.65882353],
        [0.5372549 , 0.56470588, 0.63921569],
        [0.52941176, 0.55686275, 0.63137255],
        ...,
        [0.54901961, 0.59607843, 0.49019608],
        [0.54117647, 0.56470588, 0.48627451],
        [0.59607843, 0.62745098, 0.5372549 ]],

       ...,

       [[0.43921569, 0.51764706, 0.38039216],
        [0.42745098, 0.51372549, 0.38039216],
        [0.41568627, 0

In [ ]:
print(x_train)

420    [[[53, 55, 60], [47, 50, 53], [47, 50, 59], [6...
566    [[[154, 146, 135], [152, 145, 131], [144, 138,...
65     [[[232, 236, 246], [231, 235, 248], [232, 235,...
78     [[[246, 246, 248], [247, 247, 249], [248, 248,...
254    [[[158, 149, 139], [184, 176, 165], [205, 196,...
                             ...                        
553    [[[232, 235, 247], [233, 237, 248], [232, 236,...
555    [[[175, 181, 182], [159, 159, 166], [161, 161,...
676    [[[173, 171, 184], [177, 175, 186], [178, 176,...
836    [[[149, 159, 171], [150, 159, 172], [152, 160,...
471    [[[62, 73, 77], [62, 73, 79], [63, 74, 77], [6...
Name: Image, Length: 678, dtype: object


In [ ]:
x_train_scaled = []
x_test_scaled = []
for i in range(848):
  if(i in x_train):
    x_train_scaled.append(np.array(x_train[i])/255.0)
  else:
    x_test_scaled.append(np.array(x_test[i])/255.0)
    

In [ ]:
len(x_train_scaled)

678

In [ ]:
len(x_test_scaled)

170

In [ ]:
x_train_scaled[0]

array([[[0.68627451, 0.72156863, 0.75686275],
        [0.69019608, 0.71764706, 0.75686275],
        [0.69803922, 0.7254902 , 0.76470588],
        ...,
        [0.77647059, 0.77647059, 0.79607843],
        [0.77647059, 0.77254902, 0.79215686],
        [0.77254902, 0.76862745, 0.78823529]],

       [[0.68235294, 0.72156863, 0.75686275],
        [0.68235294, 0.71764706, 0.75294118],
        [0.69019608, 0.71764706, 0.75686275],
        ...,
        [0.76078431, 0.77254902, 0.79215686],
        [0.76078431, 0.76862745, 0.78823529],
        [0.76078431, 0.76470588, 0.78431373]],

       [[0.67058824, 0.70588235, 0.74117647],
        [0.6745098 , 0.70980392, 0.74509804],
        [0.67843137, 0.71372549, 0.74901961],
        ...,
        [0.72941176, 0.74901961, 0.77254902],
        [0.72941176, 0.74901961, 0.77254902],
        [0.72941176, 0.74901961, 0.77254902]],

       ...,

       [[0.61176471, 0.60392157, 0.61960784],
        [0.6627451 , 0.65490196, 0.6627451 ],
        [0.68627451, 0

In [ ]:
x_test_scaled[0]

array([[[0.80784314, 0.8       , 0.85098039],
        [0.80784314, 0.8       , 0.85098039],
        [0.80784314, 0.8       , 0.85098039],
        ...,
        [0.20784314, 0.18431373, 0.2       ],
        [0.51764706, 0.48235294, 0.48235294],
        [0.5254902 , 0.49019608, 0.49411765]],

       [[0.80784314, 0.8       , 0.84705882],
        [0.80784314, 0.8       , 0.84705882],
        [0.80784314, 0.8       , 0.84705882],
        ...,
        [0.22352941, 0.2       , 0.20784314],
        [0.51764706, 0.48627451, 0.48235294],
        [0.53333333, 0.49803922, 0.50196078]],

       [[0.80784314, 0.8       , 0.84313725],
        [0.80784314, 0.8       , 0.84313725],
        [0.80784314, 0.8       , 0.84313725],
        ...,
        [0.23137255, 0.20784314, 0.20784314],
        [0.53333333, 0.50196078, 0.49411765],
        [0.54509804, 0.50980392, 0.51372549]],

       ...,

       [[0.34509804, 0.42745098, 0.39215686],
        [0.36470588, 0.44705882, 0.42745098],
        [0.38039216, 0

In [ ]:
feature_extractor = "https://tfhub.dev/google/tf2-preview/mobilenet_v2/feature_vector/4"
pretrained_model_without_top_layer = hub.KerasLayer(
feature_extractor, input_shape = (224,224,3), trainable = False)

In [ ]:
model = tf.keras.Sequential([
    pretrained_model_without_top_layer,
    tf.keras.layers.Dense(128),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(2)
])

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 keras_layer (KerasLayer)    (None, 1280)              2257984   
                                                                 
 dense (Dense)               (None, 128)               163968    
                                                                 
 dropout (Dropout)           (None, 128)               0         
                                                                 
 dense_1 (Dense)             (None, 2)                 258       
                                                                 
Total params: 2,422,210
Trainable params: 164,226
Non-trainable params: 2,257,984
_________________________________________________________________


In [ ]:
model.compile(
    optimizer="adam",
    loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    metrics=["acc"]
)

In [ ]:
x_train_scaled = np.array(x_train_scaled)

In [ ]:
y_train1 = np.array(y_train)

In [ ]:
x_test_scaled = np.array(x_test_scaled)
y_test1 = np.array(y_test)

In [ ]:
model.fit(x_train_scaled, y_train1, validation_data=(x_test_scaled, y_test),epochs = 10,verbose=2)

Epoch 1/10
22/22 - 21s - loss: 0.5732 - acc: 0.7168 - val_loss: 0.6837 - val_acc: 0.6176 - 21s/epoch - 957ms/step
Epoch 2/10
22/22 - 21s - loss: 0.4973 - acc: 0.7699 - val_loss: 0.6902 - val_acc: 0.6471 - 21s/epoch - 955ms/step
Epoch 3/10
22/22 - 21s - loss: 0.4711 - acc: 0.7935 - val_loss: 1.1031 - val_acc: 0.6471 - 21s/epoch - 955ms/step
Epoch 4/10
22/22 - 21s - loss: 0.5315 - acc: 0.7463 - val_loss: 0.7719 - val_acc: 0.5647 - 21s/epoch - 956ms/step
Epoch 5/10
22/22 - 21s - loss: 0.3967 - acc: 0.7994 - val_loss: 0.7528 - val_acc: 0.6000 - 21s/epoch - 957ms/step
Epoch 6/10
22/22 - 21s - loss: 0.3580 - acc: 0.8481 - val_loss: 0.7702 - val_acc: 0.5471 - 21s/epoch - 959ms/step
Epoch 7/10
22/22 - 21s - loss: 0.3708 - acc: 0.8378 - val_loss: 0.8380 - val_acc: 0.6000 - 21s/epoch - 958ms/step
Epoch 8/10
22/22 - 21s - loss: 0.3523 - acc: 0.8525 - val_loss: 0.8413 - val_acc: 0.5824 - 21s/epoch - 957ms/step
Epoch 9/10
22/22 - 21s - loss: 0.3147 - acc: 0.8496 - val_loss: 0.9164 - val_acc: 0.5647

In [ ]:
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
pred = model.predict(x_test_scaled)


In [ ]:
prd = np.argmax(pred,axis=1)
prd

array([1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0])

In [ ]:
import tensorflow_datasets as tfds
import tensorflow as tf
from sklearn.metrics import confusion_matrix


In [ ]:
confusion_matrix(prd, y_test1)

array([[ 9, 20],
       [51, 90]])

In [ ]:
from sklearn import metrics
print(metrics.classification_report(y_test1,prd))

              precision    recall  f1-score   support

           0       0.31      0.15      0.20        60
           1       0.64      0.82      0.72       110

    accuracy                           0.58       170
   macro avg       0.47      0.48      0.46       170
weighted avg       0.52      0.58      0.54       170

